name: Build Rhino Plugin
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet build --configuration Release
      - name: Upload RHP
        uses: actions/upload-artifact@v3
        with:
          name: RhinoPlugin
          path: bin/Release/net7.0-windows/EnhancedLayerStates.rhp
